version: "3.7"

services:
    api:
        build: ./api
        container_name:  api
        restart: always
        environment: 
            - APP_NAME=FlaskApp
            - POSTGRES_USER=invoice_app
            - POSTGRES_PASSWORD=invoice_secret
            - POSTGRES_DB=invoice
        env_file:
            ./api/.env
        volumes:
            - './api:/api'
        ports:
          - 5000:5000
    
    frontend:
      build: ./frontend
      container_name: client
      restart: always
      env_file: ./frontend/.env
      volumes:
        - './frontend:/app'
      expose:
        - 8080
      ports: 
        - 8080:8080
    db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=invoice_app
        - POSTGRES_PASSWORD=invoice_secret
        - POSTGRES_DB=invoice

volumes:
  postgres_data: